"""pricing + menu price

Revision ID: 0c334c525870
Revises: 0b3f45ab6fa6
Create Date: 2026-09-09 03:44:52.016831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c334c525870'
down_revision: Union[str, None] = '0b3f45ab6fa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dynamic_pricing_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('max_discount_percentage', sa.Integer(), nullable=False),
    sa.Column('start_intervention_time', sa.Time(), nullable=False),
    sa.Column('broadcast_whatsapp', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('pricing_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('time_interval', sa.Time(), nullable=False),
    sa.Column('discount_percentage', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['dynamic_pricing_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('menus', sa.Column('price', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menus', 'price')
    op.drop_table('pricing_schedules')
    op.drop_table('dynamic_pricing_rules')
    # ### end Alembic commands ###
